packaging_format = 2

id = "duniter"
name = "Duniter"
description.en = "Crypto-currency software to operate Ğ1 libre currency"
description.fr = "Logiciel de cryptomonnaie pour faire fonctionner la monnaie libre Ğ1"

version = "1.8.5~ynh1"

maintainers = ["Moul"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://duniter.org"
code = "https://git.duniter.org/nodes/typescript/duniter"

[integration]
yunohost = ">= 11.1.19"
architectures = ["amd64", "armhf"]
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        format = "deb"
        rename = "duniter-server-v1.8.5-linux-x64.deb"
        amd64.url = "https://git.duniter.org/nodes/typescript/duniter/uploads/70062d5872b9b621967dcee184ae07d8/duniter-server-v1.8.5-linux-x64.deb"
        amd64.sha256 = "1682b198788e2c9cbf7844ab3ceb9a1776e850873e3e9ed45ba077fda0611bf4"
        armhf.url = "https://git.duniter.org/nodes/typescript/duniter/uploads/8773273a64956cb02de555ec72e4d2bd/duniter-server-v1.8.5-linux-armv7l.deb"
        armhf.sha256 = "498e3a7766e167887de2d71dd43ffa6c1add11f976bf00e2a44ccc3cec5d5da0"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.add_url = ["/webmin"]

    api.url = "/bma"
    api.additional_urls = "/ws2p"
    api.auth_header = false
    api.allowed = "visitors"

    apis.url = "/bma"
    apis.additional_urls = "/ws2p"
    apis.auth_header = false
    apis.allowed = "visitors"
